backend:
  name: git-gateway
  branch: master
collections:
  - name: posts
    label: Posts
    folder: src/routes/posts
    create: true
    fields:
      - name: title
      - name: body
        widget: markdown
      - name: image
        widget: image
media_folder: 'static/uploads'
public_folder: '/uploads'
