backend:
  name: git-gateway
  branch: master
collections:
  - name: posts
    label: Posts
    folder: src/routes/posts
    create: true
    fields:
      - name: title
      - name: publish
        widget: datetime
      - name: body
        widget: markdown
      - name: image
        widget: image
  - name: curation-team
    label: Curation Team
    slug: '{{name}}'
    folder: src/collections/curation-team
    create: true
    fields:
      - name: name
      - name: slug
      - name: role
        widget: select
        options: [Curator, Senior Curator]
      - name: style_tags
        widget: list
        allow_add: true
      - name: favorite_map
        widget: object
        fields:
          - name: name
          - name: url
      - name: bio
        widget: markdown
      - name: image
        widget: image
media_folder: 'static/uploads'
public_folder: '/uploads'
